import type { Metadata } from "next";
import "../globals.css";
import HomeContextProvider from "../context/homeContext/homeContext";
import Chat from "../components/chatUI/chat";
import CreateButton from "../components/recipes/createButton";
import HomeButton from "../components/shared/homeButton";
import RecipesButton from "../components/shared/recipesButton";




export const metadata: Metadata = {
  title: "Recipes App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <HomeContextProvider>
          {children}
          <CreateButton />
          <Chat />
          <HomeButton />
          <RecipesButton />
        </HomeContextProvider>
      </body>
    </html>
  );
}
