import type { Metadata } from "next";
import "../globals.css";
import HomeContextProvider from "../context/homeContext/homeContext";
import Chat from "../components/chatUI/chat";


export const metadata: Metadata = {
  title: "Recipes App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <HomeContextProvider>
          {children}
          <Chat />
        </HomeContextProvider>
      </body>
    </html>
  );
}
